M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, March 15, 2023 at 08:38:18 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-15T20:38:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.4825Y-3.7579
X5.71Y-3.7579
T2
X5.2461Y-3.8976
X5.9465Y-3.8976
T0
M30
